job_logging:
  loggers:
    large_gcs:
      level: INFO
    large_gcs.graph:
      level: INFO
    large_gcs.algorithms:
      level: INFO
    large_gcs.cost_estimators:
      level: INFO
    large_gcs.domination_checkers:
      level: INFO