repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args: ["--remove-unused-variables", "--remove-all-unused-imports", "--recursive", "--in-place"]  # Only remove unused variables
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.4  # Use the latest stable release
    hooks:
      - id: docformatter
        args: ['--in-place', '--recursive']

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files"]

