_target_: large_gcs.domination_checkers.sampling_containment_domination_checker.ReachesCheaperLastPosSamplingContainment

num_samples_per_vertex: 1
should_use_candidate_sol_as_sample: false
containment_condition: -1