_target_: large_gcs.domination_checkers.sampling_containment_double_domination_checker.ReachesCheaperLastPosSamplingContainmentDouble

num_samples_per_vertex: 1
should_use_candidate_sol: false
containment_condition: -1