defaults:
  - algorithm: gcs_astar
  - cost_estimator: shortcut_edge #factored_collision_free #shortcut_edge
  - hydra: hydra

graph_name: "cg_trichal4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: false

# cost_estimator:
#   shortcut_edge_cost_factory: "large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_cost_factory_over_obj_weighted"
# contact_shortcut_edge_cost_factory_over_obj_weighted
# contact_shortcut_edge_cost_factory_under

save_visualization: true
save_to_wandb: true