defaults:
  - algorithm: gcs_astar_convex_restriction
  - cost_estimator: shortcut_edge
  - hydra: hydra

graph_name: "cg_trichal2"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: false

# cost_estimator:
#   obj_multiplier: 100
#   use_combined_gcs: true
#   shortcut_edge_cost_factory: "large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_cost_factory_over_obj_weighted"
algorithm:
  reexplore_level: 'NONE'
  tiebreak: 'FIFO'

save_visualization: true
save_to_wandb: false

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      graph_name: cg_simple_2, cg_simple_3, cg_trichal2