defaults:
  - algorithm: gcs_naive_astar
  - cost_estimator: shortcut_edge
  - hydra: hydra

graph_name: "cg_trichal2"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: false

algorithm:
  reexplore_level: 'NONE'
  tiebreak: 'FIFO'

save_visualization: true
save_to_wandb: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      graph_name: cg_simple_2, cg_simple_3, cg_trichal2, cg_trichal4