defaults:
  - algorithm: gcs_astar_convex_restriction
  - cost_estimator: factored_collision_free #shortcut_edge
  - hydra: hydra

graph_name: "cg_maze_a2"
# cost_estimator:
#   shortcut_edge_cost_factory: "large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_cost_factory_over_obj_weighted"
algorithm:
  should_reexplore: true
  tiebreak: 'LIFO'

save_visualization: true
save_to_wandb: true