defaults:
  - algorithm: gcs_astar_reachability
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_cheaper_sampling_pairwise
  - hydra: hydra

graph_name: "cg_trichal4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true


cost_estimator:
  # USE L1 NORM SHORTCUT EDGE COST
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1_norm_cost_factory_over_obj_weighted

domination_checker:
  num_samples_per_vertex: 10

save_visualization: true
save_to_wandb: true

hydra:
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.algorithms:
        level: DEBUG
      large_gcs.cost_estimators:
        level: INFO
  mode: MULTIRUN
  sweeper:
    params:
      domination_checker: reaches_new_sampling, reaches_cheaper_sampling, reaches_new_containment, reaches_cheaper_containment 
      graph_name: cg_simple_3, cg_trichal4, cg_maze_b1, cg_maze_b3
