defaults:
  - algorithm: gcs_astar_convex_restriction
  - cost_estimator: factored_collision_free #shortcut_edge
  - hydra: hydra

graph_name: "cg_radialsort_a1" #"cg_maze_a2"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: false

cost_estimator:
  obj_multiplier: 100
algorithm:
  reexplore_level: 'NONE'
  tiebreak: 'FIFO'

save_visualization: true
save_to_wandb: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      cost_estimator.use_combined_gcs: false, true
      algorithm.reexplore_level: PARTIAL, NONE
