defaults:
  - algorithm: gcs_star_eps_suboptimal
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_new_last_pos_containment
  - hydra: hydra

graph_name: "cg_trichal4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true


cost_estimator:
  # USE L1 NORM SHORTCUT EDGE COST
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1norm_cost_factory_obj_weighted

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      domination_checker: reaches_new_last_pos_containment, reaches_new_containment
      # domination_checker: reaches_cheaper_last_pos_sampling, reaches_cheaper_sampling
      # domination_checker: reaches_new_last_pos_sampling, reaches_new_sampling, reaches_cheaper_last_pos_sampling, reaches_cheaper_sampling
      # graph_name: cg_trichal4, cg_stackpush_d2, cg_maze_b1
