defaults:
  - algorithm: gcs_star_eps_suboptimal
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_cheaper_sampling_pairwise
  - hydra: hydra

graph_name: "cg_trichal4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true


cost_estimator:
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l2norm_cost_factory_obj_weighted

domination_checker:
  num_samples_per_vertex: 200

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

hydra:
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.algorithms:
        level: DEBUG
      large_gcs.cost_estimators:
        level: INFO
  mode: MULTIRUN
  sweeper:
    params:
      domination_checker: reaches_new_sampling, reaches_new_sampling_pairwise, reaches_cheaper_sampling, reaches_cheaper_sampling_pairwise
      graph_name: cg_trichal4, cg_maze_b1
