defaults:
  - _self_
  - algorithm: gcs_star_eps_suboptimal
  - cost_estimator: shortcut_edge_cfree
  - domination_checker: reaches_cheaper_sampling
  - hydra: hydra

graph_name: "cg_simple_1"
heuristic_inflation_factor: 10
should_add_const_edge_cost: true
const_edge_cost: 1e-3

cost_estimator:
  shortcut_edge_cost_factory: "large_gcs.graph.cfree_cost_constraint_factory.shortcut_edge_l2norm_cost_factory"

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

hydra:
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.algorithms:
        level: DEBUG
      large_gcs.cost_estimators:
        level: INFO
  mode: RUN