defaults:
  - algorithm: ixg_star
  - hydra: hydra

graph_name: "cg_simple_4"

should_use_incremental_graph: false
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

algorithm:
  heuristic_inflation_factor: 10

hydra:
  mode: MULTIRUN
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.graph:
        level: INFO
      large_gcs.algorithms:
        level: INFO
  sweeper:
    params:
      # Times out
      graph_name: cg_simple_4, cg_maze_b1