defaults:
  - algorithm: gcs_star
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_cheaper_sampling
  - hydra: hydra

graph_name: "cg_trichal4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true


cost_estimator:
  # USE L1 NORM SHORTCUT EDGE COST
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1_norm_cost_factory_over_obj_weighted

# Note: Comment this out if not using sampling domination checkers
domination_checker:
  num_samples_per_vertex: 10

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

hydra:
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.algorithms:
        level: INFO
      large_gcs.cost_estimators:
        level: INFO
  mode: MULTIRUN
  sweeper:
    params:
      domination_checker.num_samples_per_vertex: 'range(10, 1001, 50)'
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${domination_checker.num_samples_per_vertex}_samples  # Customizing the run directory structure
    subdir: ""  # Ensure no additional subdir is created
