defaults:
  - algorithm: gcs_star_eps_suboptimal
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_new_last_pos_sampling
  - hydra: hydra

graph_name: "cg_simple_4"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true
# L2 NORM VERTEX COST
# should_use_l1_norm_vertex_cost: false


cost_estimator:
  # L1 Norm Shortcut Edge Cost
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1norm_cost_factory_obj_weighted
  # L2 Norm Shortcut Edge Cost
  # shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1norm_cost_factory_obj_weighted

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

# algorithm:
#   load_checkpoint_log_dir: "outputs/2024-06-04/00-48-14"
#   override_wall_clock_time: 50 # WARNING, use with caution

domination_checker:
  num_samples_per_vertex: 1
  should_use_candidate_sol: false

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      graph_name: cg_simple_4, cg_stackpush_d2, cg_maze_b1
