defaults:
  - algorithm: gcs_astar_reachability
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_new_sampling
  - hydra: hydra

graph_name: "cg_maze_b1"
should_use_incremental_graph: true
should_incl_simul_mode_switches: false
should_add_const_edge_cost: true
# USE L1 NORM VERTEX COST
should_use_l1_norm_vertex_cost: true


cost_estimator:
  # USE L1 NORM SHORTCUT EDGE COST
  shortcut_edge_cost_factory: large_gcs.graph.contact_cost_constraint_factory.contact_shortcut_edge_l1_norm_cost_factory_over_obj_weighted

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: true

algorithm:
  should_invert_S: true

hydra:
  job_logging:
    loggers:
      large_gcs:
        level: INFO
      large_gcs.algorithms:
        level: INFO
      large_gcs.cost_estimators:
        level: INFO
  mode: MULTIRUN
  sweeper:
    params:
      # domination_checker: reaches_new_sampling, reaches_new_containment
      graph_name: cg_trichal4, cg_stackpush_d2, cg_maze_b1
